# Generated by Django 5.2.17 on 2026-09-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('INTERNSHIP', 'Internship'), ('ORGANIZATION', 'Organization'), ('COMPETITION', 'Competition'), ('VOLUNTEERING', 'Volunteering'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_ongoing', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('year', models.TextField()),
            ],
        ),
    ]
