# Generated by Django 5.2.17 on 2026-09-26 13:14

from django.conf import settings
from django.db import migrations, models

EDITOR_GROUP = "Editor"


def create_editor_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    group, _ = Group.objects.get_or_create(name=EDITOR_GROUP)
    # Editors may UPDATE only
    group.permissions.set(
        Permission.objects.filter(codename__in=["change_experience", "change_project"])
    )


def remove_editor_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name=EDITOR_GROUP).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_project_starred_by"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(create_editor_group, remove_editor_group),
    ]